### ISSUE TITLE
.editorconfig files for DFMT

### ISSUE THREAD

**Issue by StefanHub** [DDT-IDE/DDT#136]
My .editorconfig file does not get recognized by DFMT. Where should I place it? I tried in the same folder where the source files are and in the projects folder.

(My environment: Eclipse 4.5.2, DDT 1.0, Windows)

**Comment by bruno-medeiros** [comment]
Were you formatting a single file by pressing Ctrl+Shift+F in the editor, or formatting a whole DUB bundle by invoking "Format DUB package" in the Project Explorer? The later unfortunately ignores .editorconfig files, but that is due to a dfmt bug.

If it's the former you were trying (Ctrl+Shift+F), what .editorconfig file you used? Are you using latest dfmt ( https://github.com/Hackerpilot/dfmt/releases/tag/v0.5.0-beta3)  Did you try something simple like: 
``` 
[*]
indent_size = 8
```
to see if it works?

**Comment by StefanHub** [comment]
Yes, I was formatting for a single file (on editor save). After a few experiments with DFMT only I found out that my dfmt.exe did not do the formatting in the way that I expected.
After a rebuild with DUB it works now. Building with make fails and build.bat sometimes works sometimes not. Very strange.
