### ISSUE TITLE
Server Error - The selection did not contain any resources that can run on a server

### ISSUE THREAD

**Issue by mbierlee** [DDT-IDE/DDT#142]
DDT 1.0.1

When you have just started Eclipse and immediately want to run a project (using default shortcut ctrl-F11), you are presented with the following error dialog:

Server Error - The selection did not contain any resources that can run on a server.

When dismissing the dialog and pressing ctrl-F11 again the build will start and the program will run. This only happens once every start-up.

(Note that I have observed this issue to exist since before 1.0.0 already)

**Comment by bruno-medeiros** [comment]
That is strange, I don't recognize that error message... I don't think it's coming from DDT. If you go to `Preferences > Run/Debug > Launching` what option do you have for "Launch Operation" ?

**Comment by mbierlee** [comment]
The launch configuration configured is the name of the program. It is the only configuration.

**Comment by mbierlee** [comment]
The configured launch operation is:
"Launch the selected resource or active editor. If not launchable:"
"Launch the associated project"

**Comment by bruno-medeiros** [comment]
What happens if you start Eclipse, and right after, select the D project in Project Explorer and press ctrl-F11 ?

**Comment by mbierlee** [comment]
It immediately runs then without problem. When selecting the opened editor (from the same project) it doesn't. I do have "Link with editor" enabled.

**Comment by bruno-medeiros** [comment]
Could you try installating DDT into just the plaftorm runtime: http://archive.eclipse.org/eclipse/downloads/drops4/R-4.5-201506032000/#PlatformRuntime and then start that Eclipse on your workspace, and try the same launch workflow? I wanna verify that such error message is not caused by DDT or a core Eclipse plug-in, but some other plug-in. That sounds like a message from the Eclipse WTP plugins (https://www.eclipse.org/webtools/)

It's probably not DDT's fault, but I'll need to be able to replicated it myself to check that.

**Comment by mbierlee** [comment]
I installed the platform runtime, both the version you linked and the one I'm running normally (4.5.2) and don't observe the problem. To be clear, my normal installation is an Eclipse CDT package.

I'm closing this issue as it's most definitely a platform issue.

**Comment by mbierlee** [comment]
And as assumed, after uninstalling the Eclipse WTP plugins, the problem is gone.
